server:
  port: ${PORT}

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  doc:
    swagger-ui:
      disable-swagger-default-url: true
      path: /swagger
  datasource:
    url: ${URL_DB}
    username: ${USERNAME_DB}
    password: ${PSS}
    driver-class-name: ${DRIVE}
  data:
    redis:
      enabled: false
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
    password: ${JASYPT_ENCRYPTOR}

